# k8s-demo.yaml
# Demo cách deploy app và inject secret bằng Kubernetes
# Chạy bằng lệnh: kubectl apply -f k8s-demo.yaml

# ----- 1. Định nghĩa Secret -----
# Secret này chứa "bí mật" của chúng ta, đã được mã hóa Base64
# (Giá trị "RMOieSBsYSBzZWNyZXQgdOG7qyBLdWJlcm5ldGVzIQ==" là Base64 của
# "Day la secret tu Kubernetes!")
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  # key: MY_SECRET
  # value: "Day la secret tu Kubernetes!" (encoded as base64)
  MY_SECRET: RMOieSBsYSBzZWNyZXQgdOG7qyBLdWJlcm5ldGVzIQ==

---
# ----- 2. Định nghĩa Deployment -----
# Tạo 1 pod chạy image 'hardened-app'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: hardened-app
          # Rất quan trọng: Dùng IfNotPresent để K8s lấy image đã build local (trong Minikube)
          # thay vì cố gắng pull từ Docker Hub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

          # === SECRET MANAGEMENT ===
          # Lấy giá trị cho biến môi trường MY_SECRET
          # từ đối tượng Secret tên 'my-app-secret'
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: MY_SECRET

---
# ----- 3. Định nghĩa Service -----
# Mở cổng 30080 (NodePort) để truy cập ứng dụng từ bên ngoài cluster
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80 # Port nội bộ của service
      targetPort: 3000 # Port của container (app)
      nodePort: 30080 # Port mở ra trên máy host (để truy cập)
